feat: report-problem base
gig3r-com/giger pull request #4
Opened 2023-09-27 18:25 UTC by NightmareFuryRemi

2023-09-30 09:47 UTC, EvilProfesseur requested changes

2023-10-03 18:41 UTC, krzysztofkleba reviewed
just to be marked as reviewer

2023-10-03 18:53 UTC, krzysztofkleba requested changes

2023-10-03 18:53 UTC, krzysztofkleba commented on frontend/src/shared/components/report-problem/reportProblem.css
try to remove  `frontend/src/shared/components/report-problem/reportProblem.css` and `frontend/src/shared/components/report-problem/reportProblem.min.css` -> then see if your app still working, if yes we dont need to push them into repository and simply this files are redundant.

2023-10-03 18:53 UTC, krzysztofkleba commented on frontend/src/shared/services/reportProblem.service.ts
> +export function userReportProblem() {
rename it to `useReportProblem`

2023-10-08 09:58 UTC, EvilProfesseur commented
Controls should be in line with the body of the component. 
![image](https://github.com/gig3r-com/giger/assets/14939852/3354fa86-7b33-4f04-82b6-911cae902bfe)

2023-10-08 10:01 UTC, EvilProfesseur commented
"Describe the problem" text is displayed in a wrong font

2023-10-31 22:20 UTC, EvilProfesseur approved these changes

2023-10-31 22:20 UTC, merged